<?php
/*
module : alterFormAtlas
Alteration du formulaire d'ajout de picto surcharge
Alteration de la redirection en fonction de l'entrée
*/

function alterFormAtlas_form_book_les_pictos_surcharge_node_form_alter(&$form, &$form_state){

	global $base_url;

	//test si on vient de tous-les-pictos-par-sous-bassin
	if(isset($_GET['code'])){		
		
		//Get param in url for pager
		if(isset($_GET["pager"])) $pager = urldecode($_GET["pager"]);		
		if(isset($_GET["ssbassin"])) $ssbassin = urldecode($_GET["ssbassin"]);
		
		//Set message to user
		drupal_set_message( "ATTENTION : Vos modifications ne seront enregistrés que cette nuit.", $type = 'warning', $repeat = TRUE); 
		
		//Alter title field value
		$form['title']['#default_value'] = 'picto surcharge sur: '.$_GET['code'];		

		//Alter value of other fields
		$form['#after_build'][] = 'alterFormAtlas_after_build';

		//Set redirect to html cached pages
		unset($form['destination']);				
		$form['#redirect'] = $base_url."/cache/projet-atlas/tous-les-pictos-par-sous-bassin_ssbassin=".$ssbassin."&pager=".$pager.".html";		

	//test si on vient de pictos-par-sous-bassin
	}else{

		//Get param in url for pager
		if(isset($_GET["pager"])) $pager = urldecode($_GET["pager"]);	
		if(isset($_GET["ssbassin"])) $ssbassin = urldecode($_GET["ssbassin"]);		

		//Set redirect to normal pages
  		unset($form['destination']);	  	
		$form['#redirect'] = $base_url."/projet-atlas/pictos-par-sous-bassin&ssbassin=".$ssbassin."&pager=".$pager;		
		
	}

}

/**
 * Modify CCK form elements on the example node form.
 */
function alterFormAtlas_after_build($form, &$form_state) {
  
  	//Add css to hide some field - Specific field
	if($_GET['genre'] == 'interet' && $_GET['type'] == 'botanique') drupal_add_css(drupal_get_path('module', 'alterFormAtlas') .'/alterFormAtlas.css');
	else if($_GET['genre'] == 'interet' && $_GET['type'] == 'ornithologie') drupal_add_css(drupal_get_path('module', 'alterFormAtlas') .'/alterFormAtlas.css');
	else if($_GET['genre'] == 'interet' && $_GET['type'] == 'herpetologie') drupal_add_css(drupal_get_path('module', 'alterFormAtlas') .'/alterFormAtlas.css');
	else if($_GET['genre'] == 'interet' && $_GET['type'] == 'mamifere') drupal_add_css(drupal_get_path('module', 'alterFormAtlas') .'/alterFormAtlas.css');
	else if($_GET['genre'] == 'interet' && $_GET['type'] == 'chiroptere') drupal_add_css(drupal_get_path('module', 'alterFormAtlas') .'/alterFormAtlas.css');	
	else if($_GET['genre'] == 'interet' && $_GET['type'] == 'fauneM') drupal_add_css(drupal_get_path('module', 'alterFormAtlas') .'/alterFormAtlas.css');	
	else if($_GET['genre'] == 'interet' && $_GET['type'] == 'floreM') drupal_add_css(drupal_get_path('module', 'alterFormAtlas') .'/alterFormAtlas.css');	

	//Alter value to add id for the node
	$form['field_book_genre_picto_surcharge'][0]['value']['#value'] = $_GET['genre'];
	$form['field_book_type_picto_surcharge'][0]['value']['#value'] = $_GET['type'];		

  return $form;
}